### PR TITLE
Windows compatibility fixes and additional IDE excludes

### PR DESCRIPTION
**Pull request by willstahl**

### CODE REVIEW

**Review by ewoolsey — CHANGES_REQUESTED** [review]
@willstahl have you tested this gzip algorithm and successfully stored code on chain? I'm getting this error:

```
Error: CosmosSDK error: ChainResponse { code: Err(6), data: Some([]), log: "rpc error: code = Unknown desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm bytecode could not be deserialized. Deserialization error: \"Unknown opcode 192\": create wasm contract failed [CosmWasm/wasmd@v0.29.2/x/wasm/keeper/keeper.go:213] With gas wanted: '1000000000' and gas used: '5017841' : unknown request" }
```

**Comment by willstahl** [comment]
This actually sounds like an issue with the recent wasm-opt change but I can't be 100% sure. I would get this exact error when I ran the latest version of wasm-opt

**Comment by ewoolsey** [comment]
> This actually sounds like an issue with the recent wasm-opt change but I can't be 100% sure. I would get this exact error when I ran the latest version of wasm-opt

I tried both with and without the wasm-opt feature enabled. I have no issues on the latest dev, but I get this error when I checkout this PR. I'm pretty sure this PR is causing the issue.

**Comment by ewoolsey** [comment]
> This actually sounds like an issue with the recent wasm-opt change but I can't be 100% sure. I would get this exact error when I ran the latest version of wasm-opt (binaryen verskon_112) instead of the older version we had installed through npm (binaryen version_105). I think it's unzipping properly because it's complaining about an opcode it doesn't know about, unless that's the default error when it encounters a binary it doesn't understand. If it's an issue w/ the wasm-opt version it could be caused by Noria's cosmwasm version perhaps? Either way I think we can diagnose which is the problem pretty straightforwardly.

I think you might actually be on the right track here. version 112 seems to be giving some grief. looks like we'll need to manually change to 105.

**Comment by ewoolsey** [comment]
Yep, so the errors I was seeing were the result of accidentally compiling the bins with nightly rather than stable. I have now specified which channel to compile on inside the build method.

**Pull request merged**
